###
### Copyright 2011, Boundary
###
### Licensed under the Apache License, Version 2.0 (the "License");
### you may not use this file except in compliance with the License.
### You may obtain a copy of the License at
###
###     http://www.apache.org/licenses/LICENSE-2.0
###
### Unless required by applicable law or agreed to in writing, software
### distributed under the License is distributed on an "AS IS" BASIS,
### WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
### See the License for the specific language governing permissions and
### limitations under the License.
###


#!/usr/bin/ruby

require 'rubygems'
require 'json'
require 'excon'
require 'base64'

API_URL = "https://api.boundary.com"

def auth_encode(creds)
  auth = Base64.encode64(creds).strip
  auth.gsub("\n","")
end

def create_event(url, headers)
  event = {
        :severity => "ERROR",
        :status => "OPEN",
        :source => {
                :ref => "sample",
                :type => "meter",
                :name => "samplesource"
                   },
        :sender => {
                :ref => "sample",
                :type => "sampleruby",
                :name => "create_event.rb"
                   },
        :properties => {
                :eventKey => "53442423"
                       },
        :tags => ["example","test","stuff","ruby"],
        :title => "sample ruby event",
        :message => "details of the event generated by Ruby script",
        :fingerprintFields => ["eventKey"]
    }

  event_json = event.to_json
  response = Excon.post(url, :headers => headers, :body => event_json)
  response.headers["Location"]
end

def main
  if ARGV[0] == "-i" && ARGV[2] == "-a"
    auth = auth_encode("#{ARGV[3]}:")
    headers = {"Authorization" => "Basic #{auth}", "Content-Type" => "application/json"}

    event = create_event("#{API_URL}/#{ARGV[1]}/events", headers)
    puts "An event was created at #{event}"
  else
    puts "./create_event.rb -i ORGID -a APIKEY"
  end
end

main
